### ISSUE TITLE
Unable to start recording in Repeato.app although the library has been added to the project

### ISSUE THREAD

**Issue by tudorsss** [stoefln/RepeatoCapture#5]
Unable to start recording in Repeato.app although the library has been added to the project. It does look like, at least now, that the screenshots from the app need to be updated, but hopefully, I've done the instructions as expected.

<img width="1439" alt="Screenshot 2022-03-09 at 18 52 39" src="https://user-images.githubusercontent.com/12154831/157491133-d3dc51a0-fc09-44e9-b5ab-dc12cb2b5e48.png">
<img width="1194" alt="Screenshot 2022-03-09 at 18 53 13" src="https://user-images.githubusercontent.com/12154831/157491155-8ee68d5f-a71b-4ccf-afe7-02e67f2ecdb3.png">

**Comment by stoefln** [comment]
@tudorsss thanks very much for your report! It seems you added the library correctly. Can you maybe post the app start log printed in XCode?

**Comment by tudorsss** [comment]
[app log.txt](https://github.com/stoefln/RepeatoCapture/files/8227185/app.log.txt)

**Comment by stoefln** [comment]
@tudorsss, unfortunately, we couldn't find anything suspicious in your log. We also can't reproduce the problem with [MovieSwiftUI](https://github.com/Dimillian/MovieSwiftUI) one of the OS apps we use for testing. Can you maybe check it out, maybe you see some obvious difference?

**Comment by tudorsss** [comment]
Hi @stoefln ,

I used this project https://developer.apple.com/tutorials/swiftui/working-with-ui-controls to test Repeato. I'm getting some errors -  the "Favorites only" check-box is not caught by Reapeato. Then there's some errors. We can get on a call if you'd like, to hear more of my feedback:

calendly.com/betterqa 

<img width="1272" alt="Screenshot 2022-03-18 at 17 21 09" src="https://user-images.githubusercontent.com/12154831/159031176-0376791d-a971-4ea3-b9fa-160e0bd404f0.png">

**Comment by stoefln** [comment]
Hi @tudorsss, did you resolve the issue? Otherwise, we can check out the sample you posted...

**Comment by tudorsss** [comment]
Hi @stoefln , not really - I'd be happy to help but I think this would work better if we hop on a call.
